package inventory;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Writes inventory/handlers.yaml (調査計画.md S3): JSFTemplating handler definitions and their use in pages.
 *
 * <p>Call counts are textual (comments and inline JavaScript are not excluded), and the tags come from
 * scanning each handler method body for characteristic calls; both are approximations.
 */
final class HandlersExtractor {

    private static final Pattern CALL = Pattern.compile("(?<![\\w.$#{])([A-Za-z_]\\w*(?:\\.[A-Za-z_]\\w*)*)\\s*\\(");
    private static final Pattern PAGE_DEFINITION = Pattern.compile("<handler\\s+id=\"([^\"]+)\"");
    private static final List<String> ADMINGUI_ID_PREFIXES = List.of("gf.", "gfr.", "gfj.");

    private static final Map<String, Pattern> TAGS = tags();

    private final AdminguiTree tree;

    /** Definitions whose id was already defined elsewhere; the first one read is kept in the inventory. */
    private final List<Object> duplicateDefinitions = new ArrayList<>();

    HandlersExtractor(Path root) {
        this.tree = new AdminguiTree(root);
    }

    private static Map<String, Pattern> tags() {
        Map<String, Pattern> tags = new LinkedHashMap<>();
        tags.put("rest", Pattern.compile("RestUtil2?\\.|RestApiHandlers\\.|restRequest\\("));
        tags.put("navigation", Pattern.compile("\\.redirect\\(|\\.navigate\\(|\\.dispatch\\(|handleNavigation\\("));
        tags.put("session", Pattern.compile("getSessionMap\\(|getSession\\("));
        tags.put("hk2", Pattern.compile("ServiceLocator|getHabitat\\("));
        tags.put("uiComponent", Pattern.compile("\\bUIComponent\\b|getViewRoot\\("));
        tags.put("fileIo", Pattern.compile("\\bnew File\\(|\\bFiles\\.|InputStream|OutputStream"));
        return tags;
    }

    void write(Path output) throws Exception {
        Map<String, Map<String, Object>> handlers = new TreeMap<>();
        for (HandlerDefinitions.Definition definition : HandlerDefinitions.read(tree)) {
            keepFirst(handlers, describe(definition));
        }
        addPageDefinitions(handlers);

        Map<String, Map<String, Set<String>>> unresolved = new TreeMap<>();
        for (Path module : tree.modules()) {
            String moduleName = module.getFileName().toString();
            for (Path page : tree.pages(module)) {
                String path = tree.relative(page);
                Matcher call = CALL.matcher(AdminguiTree.read(page));
                while (call.find()) {
                    String id = call.group(1);
                    Map<String, Object> handler = handlers.get(id);
                    if (handler != null) {
                        recordCall(handler, moduleName, path);
                    } else if (ADMINGUI_ID_PREFIXES.stream().anyMatch(id::startsWith)) {
                        unresolved.computeIfAbsent(id, k -> new TreeMap<>()).computeIfAbsent(moduleName, k -> new TreeSet<>()).add(path);
                    }
                }
            }
        }
        for (Map<String, Object> handler : handlers.values()) {
            analyzeSource(handler);
            finishUsage(handler);
        }

        Path jar = tree.distributedJsftemplatingJar();
        Map<String, Object> document = new LinkedHashMap<>();
        Map<String, Object> source = new LinkedHashMap<>();
        source.put("repository", "glassfish");
        source.put("commit", ModulesExtractor.Git.head(tree.root()));
        source.put("builtinDefinitionsFrom", Files.isRegularFile(jar) ? tree.relative(jar) : "missing (build the distribution first)");
        document.put("source", source);
        document.put("summary", summary(handlers, unresolved));
        document.put("duplicateDefinitions", duplicateDefinitions);
        document.put("unresolvedCalls", unresolvedJson(unresolved));
        document.put("handlers", new ArrayList<>(handlers.values()));

        Files.createDirectories(output.getParent());
        Files.writeString(output, Yaml.write(document,
                "Generated by tools/inventory/extractor (handlers). Do not edit by hand.\n"
                        + "calls are textual matches in .jsf/.inc/.layout files; tags are heuristics from method bodies.\n"
                        + "Interpretation and notes belong in docs/as-is/jsftemplating.md."),
                StandardCharsets.UTF_8);
    }

    private Map<String, Object> describe(HandlerDefinitions.Definition definition) {
        Map<String, Object> handler = new LinkedHashMap<>();
        handler.put("id", definition.id());
        handler.put("origin", definition.origin());
        handler.put("module", definition.module() == null ? null : definition.module().getFileName().toString());
        handler.put("class", definition.className());
        handler.put("method", definition.method());
        handler.put("inputs", ios(definition.inputs()));
        handler.put("outputs", ios(definition.outputs()));
        if (definition.module() != null) {
            handler.put("sourceFile", sourceFile(definition.module(), definition.className()));
        }
        return handler;
    }

    private static List<Object> ios(List<HandlerDefinitions.Io> ios) {
        List<Object> result = new ArrayList<>();
        for (HandlerDefinitions.Io io : ios) {
            Map<String, Object> map = new LinkedHashMap<>();
            map.put("name", io.name());
            map.put("type", io.type());
            if (io.required() != null) {
                map.put("required", io.required());
            }
            if (io.defaultValue() != null) {
                map.put("defaultValue", io.defaultValue());
            }
            result.add(map);
        }
        return result;
    }

    private void addPageDefinitions(Map<String, Map<String, Object>> handlers) throws IOException {
        Map<String, Map<String, Object>> pageDefinitions = new TreeMap<>();
        for (Path module : tree.modules()) {
            for (Path page : tree.pages(module)) {
                Matcher definition = PAGE_DEFINITION.matcher(AdminguiTree.read(page));
                while (definition.find()) {
                    Map<String, Object> handler = pageDefinitions.computeIfAbsent(definition.group(1), id -> {
                        Map<String, Object> created = new LinkedHashMap<>();
                        created.put("id", id);
                        created.put("origin", "page");
                        created.put("module", module.getFileName().toString());
                        created.put("definedInPages", new ArrayList<String>());
                        return created;
                    });
                    @SuppressWarnings("unchecked")
                    List<String> definedIn = (List<String>) handler.get("definedInPages");
                    String path = tree.relative(page);
                    if (!definedIn.contains(path)) {
                        definedIn.add(path);
                    }
                }
            }
        }
        pageDefinitions.values().forEach(handler -> keepFirst(handlers, handler));
    }

    private void keepFirst(Map<String, Map<String, Object>> handlers, Map<String, Object> handler) {
        Map<String, Object> existing = handlers.putIfAbsent((String) handler.get("id"), handler);
        if (existing != null) {
            Map<String, Object> duplicate = new LinkedHashMap<>();
            duplicate.put("id", handler.get("id"));
            duplicate.put("kept", existing.get("origin") + " " + existing.getOrDefault("class", existing.get("definedInPages")));
            duplicate.put("alsoDefinedBy", handler.get("origin") + " " + handler.getOrDefault("class", handler.get("definedInPages")));
            duplicateDefinitions.add(duplicate);
        }
    }

    private String sourceFile(Path module, String className) {
        Path file = module.resolve("src/main/java").resolve(className.replace('.', '/') + ".java");
        return Files.isRegularFile(file) ? tree.relative(file) : null;
    }

    @SuppressWarnings("unchecked")
    private static void recordCall(Map<String, Object> handler, String module, String path) {
        ((Map<String, Integer>) handler.computeIfAbsent("callsByModule", k -> new TreeMap<String, Integer>())).merge(module, 1, Integer::sum);
        ((Set<String>) handler.computeIfAbsent("callFileSet", k -> new TreeSet<String>())).add(path);
    }

    @SuppressWarnings("unchecked")
    private static void finishUsage(Map<String, Object> handler) {
        Map<String, Integer> byModule = (Map<String, Integer>) handler.remove("callsByModule");
        Set<String> files = (Set<String>) handler.remove("callFileSet");
        handler.put("calls", byModule == null ? 0 : byModule.values().stream().mapToInt(Integer::intValue).sum());
        handler.put("callFiles", files == null ? 0 : files.size());
        handler.put("callsByModule", byModule == null ? Map.of() : byModule);
    }

    private void analyzeSource(Map<String, Object> handler) throws IOException {
        Object sourceFile = handler.get("sourceFile");
        if (sourceFile == null) {
            return;
        }
        String source = AdminguiTree.read(tree.root().resolve(sourceFile.toString()));
        Matcher declaration = Pattern.compile("((?:public|protected|private)?\\s*(?:static\\s+)?)void\\s+"
                + Pattern.quote(String.valueOf(handler.get("method"))) + "\\s*\\(\\s*HandlerContext").matcher(source);
        if (!declaration.find()) {
            handler.put("static", null);
            handler.put("tags", List.of());
            return;
        }
        handler.put("static", declaration.group(1).contains("static"));
        String body = JavaSource.blockAfter(source, declaration.end());
        List<String> tags = new ArrayList<>();
        for (Map.Entry<String, Pattern> tag : TAGS.entrySet()) {
            if (body != null && tag.getValue().matcher(body).find()) {
                tags.add(tag.getKey());
            }
        }
        handler.put("tags", tags);
    }

    private static Map<String, Object> summary(Map<String, Map<String, Object>> handlers, Map<String, Map<String, Set<String>>> unresolved) {
        Map<String, Object> summary = new LinkedHashMap<>();
        for (String origin : List.of("admingui", "jsftemplating", "page")) {
            List<Map<String, Object>> ofOrigin = handlers.values().stream().filter(h -> origin.equals(h.get("origin"))).toList();
            Map<String, Object> counts = new LinkedHashMap<>();
            counts.put("definitions", ofOrigin.size());
            counts.put("usedInPages", ofOrigin.stream().filter(h -> (int) h.get("calls") > 0).count());
            counts.put("calls", ofOrigin.stream().mapToInt(h -> (int) h.get("calls")).sum());
            if ("admingui".equals(origin)) {
                counts.put("nonStatic", ofOrigin.stream().filter(h -> Boolean.FALSE.equals(h.get("static"))).count());
                Map<String, Integer> byTag = new LinkedHashMap<>();
                for (String tag : TAGS.keySet()) {
                    byTag.put(tag, (int) ofOrigin.stream().filter(h -> ((List<?>) h.get("tags")).contains(tag)).count());
                }
                byTag.put("(none)", (int) ofOrigin.stream().filter(h -> ((List<?>) h.get("tags")).isEmpty()).count());
                counts.put("handlersByTag", byTag);
                counts.put("handlersByClass", byClass(ofOrigin));
            }
            summary.put(origin, counts);
        }
        summary.put("unresolvedCallIds", unresolved.size());
        return summary;
    }

    private static Map<String, Object> byClass(List<Map<String, Object>> handlers) {
        Map<String, Map<String, Integer>> byClass = new TreeMap<>();
        for (Map<String, Object> handler : handlers) {
            Map<String, Integer> counts = byClass.computeIfAbsent(String.valueOf(handler.get("class")), k -> {
                Map<String, Integer> created = new LinkedHashMap<>();
                created.put("definitions", 0);
                created.put("usedInPages", 0);
                created.put("calls", 0);
                return created;
            });
            counts.merge("definitions", 1, Integer::sum);
            counts.merge("usedInPages", (int) handler.get("calls") > 0 ? 1 : 0, Integer::sum);
            counts.merge("calls", (int) handler.get("calls"), Integer::sum);
        }
        return new LinkedHashMap<>(byClass);
    }

    private static List<Object> unresolvedJson(Map<String, Map<String, Set<String>>> unresolved) {
        List<Object> result = new ArrayList<>();
        unresolved.forEach((id, byModule) -> {
            Map<String, Object> entry = new LinkedHashMap<>();
            entry.put("id", id);
            List<String> files = new ArrayList<>();
            byModule.values().forEach(files::addAll);
            entry.put("files", files);
            result.add(entry);
        });
        return result;
    }
}
