package inventory;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.regex.Pattern;
import java.util.stream.Stream;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

/**
 * Writes inventory/help-i18n.yaml (調査計画.md S8): online help structure and links, message bundles and translations,
 * and how the help compares with the glassfish-docs clone next to the GlassFish working tree.
 */
final class HelpI18nExtractor {

    private static final Pattern LOCALIZED_PROPERTIES = Pattern.compile(".*_[a-z]{2}(_[A-Z]{2})?\\.properties");
    private static final Pattern LEADING_COMMENT = Pattern.compile("^\\s*<!--.*?-->", Pattern.DOTALL);
    private static final Pattern COPYRIGHT_FOOTER = Pattern.compile("<small>Copyright .*?</small>", Pattern.DOTALL);
    private static final Pattern WHITESPACE = Pattern.compile("\\s+");
    private static final Set<String> NON_MESSAGE_BUNDLES = Set.of("Helplinks.properties", "FieldLengths.properties", "customtheme.properties");

    /** glassfish-docs help module names that differ from the admingui module directory names. */
    private static final Map<String, String> DOCS_TO_ADMINGUI = Map.of("jms", "jms-plugin", "mail", "mail-plugin");

    private final AdminguiTree tree;
    private final Path docs;

    HelpI18nExtractor(Path root) {
        this.tree = new AdminguiTree(root);
        this.docs = root.getParent().resolve("glassfish-docs");
    }

    void write(Path output) throws Exception {
        Map<String, Path> docsModules = docsModules();

        List<Object> modules = new ArrayList<>();
        for (Path module : tree.modules()) {
            Map<String, Object> entry = module(module, docsModules.get(module.getFileName().toString()));
            if (entry != null) {
                modules.add(entry);
            }
        }

        Map<String, Object> document = new LinkedHashMap<>();
        Map<String, Object> source = new LinkedHashMap<>();
        source.put("repository", "glassfish");
        source.put("commit", ModulesExtractor.Git.head(tree.root()));
        source.put("docsRepository", Files.isDirectory(docs) ? "glassfish-docs" : "missing");
        source.put("docsCommit", Files.isDirectory(docs) ? ModulesExtractor.Git.head(docs) : null);
        document.put("source", source);
        document.put("facesSupportedLocales", supportedLocales(tree.admingui().resolve("war/src/main/webapp/WEB-INF/faces-config.xml")));
        document.put("comparisonNote", "bodyEqual ignores the leading comment block, <small>Copyright ...</small> footers and whitespace");
        document.put("modules", modules);

        Files.createDirectories(output.getParent());
        Files.writeString(output, Yaml.write(document,
                "Generated by tools/inventory/extractor (help-i18n). Do not edit by hand.\n"
                        + "Interpretation and notes belong in docs/as-is/help-i18n.md."),
                StandardCharsets.UTF_8);
    }

    private Map<String, Object> module(Path module, Path docsModule) throws Exception {
        Path help = module.resolve("src/main/help");
        Map<String, Object> bundles = messageBundles(module);
        if (!Files.isDirectory(help) && bundles.isEmpty()) {
            return null;
        }
        Map<String, Object> entry = new LinkedHashMap<>();
        entry.put("module", module.getFileName().toString());
        entry.put("messageBundles", bundles);
        if (Files.isDirectory(help)) {
            entry.put("helpLocales", subdirectories(help));
            entry.put("help", englishHelp(module, help.resolve("en/help")));
        }
        if (docsModule != null) {
            entry.put("glassfishDocs", compareWithDocs(help.resolve("en/help"), docsModule));
        }
        return entry;
    }

    private Map<String, Object> englishHelp(Path module, Path en) throws Exception {
        Set<String> pages = new TreeSet<>();
        if (Files.isDirectory(en)) {
            try (Stream<Path> files = Files.list(en)) {
                files.map(p -> p.getFileName().toString()).filter(n -> n.endsWith(".html")).forEach(pages::add);
            }
        }
        List<String> tocTargets = targets(en.resolve("toc.xml"), "tocitem");
        List<String> indexTargets = targets(en.resolve("index.xml"), "indexitem");
        Map<String, String> helpLinks = helpLinks(module);

        Set<String> referenced = new TreeSet<>();
        tocTargets.forEach(t -> referenced.add(page(t)));
        indexTargets.forEach(t -> referenced.add(page(t)));
        helpLinks.values().forEach(v -> referenced.add(stripAnchor(v)));

        Map<String, Object> help = new LinkedHashMap<>();
        help.put("htmlPages", pages.size());
        help.put("tocItems", tocTargets.size());
        help.put("indexItems", indexTargets.size());
        help.put("brokenTocTargets", missing(tocTargets.stream().map(HelpI18nExtractor::page).toList(), pages));
        help.put("brokenIndexTargets", missing(indexTargets.stream().map(HelpI18nExtractor::page).toList(), pages));
        help.put("helpLinkKeys", helpLinks.size());
        help.put("brokenHelpLinks", missing(helpLinks.values().stream().map(HelpI18nExtractor::stripAnchor).toList(), pages));
        List<String> unreferenced = pages.stream().filter(p -> !referenced.contains(p)).toList();
        help.put("unreferencedPages", unreferenced);
        return help;
    }

    private Map<String, Object> messageBundles(Path module) throws IOException {
        Map<String, Object> result = new TreeMap<>();
        Path resources = module.resolve("src/main/resources");
        if (!Files.isDirectory(resources)) {
            return result;
        }
        List<Path> files;
        try (Stream<Path> walk = Files.walk(resources)) {
            files = walk.filter(p -> p.getFileName().toString().endsWith(".properties")).sorted().toList();
        }
        for (Path file : files) {
            String name = file.getFileName().toString();
            if (NON_MESSAGE_BUNDLES.contains(name) || LOCALIZED_PROPERTIES.matcher(name).matches()) {
                continue;
            }
            String base = resources.relativize(file).toString().replace('\\', '/');
            base = base.substring(0, base.length() - ".properties".length()).replace('/', '.');
            String prefix = name.substring(0, name.length() - ".properties".length()) + "_";
            List<String> translations = new ArrayList<>();
            try (Stream<Path> siblings = Files.list(file.getParent())) {
                siblings.map(p -> p.getFileName().toString())
                        .filter(n -> n.startsWith(prefix) && LOCALIZED_PROPERTIES.matcher(n).matches())
                        .sorted()
                        .forEach(translations::add);
            }
            Map<String, Object> bundle = new LinkedHashMap<>();
            bundle.put("keys", load(file).size());
            bundle.put("translations", translations);
            result.put(base, bundle);
        }
        return result;
    }

    private Map<String, String> helpLinks(Path module) throws IOException {
        Map<String, String> result = new TreeMap<>();
        Path resources = module.resolve("src/main/resources");
        if (!Files.isDirectory(resources)) {
            return result;
        }
        try (Stream<Path> walk = Files.walk(resources)) {
            for (Path file : walk.filter(p -> p.getFileName().toString().equals("Helplinks.properties")).toList()) {
                Properties properties = load(file);
                properties.stringPropertyNames().forEach(k -> result.put(k, properties.getProperty(k).trim()));
            }
        }
        return result;
    }

    private Map<String, Object> compareWithDocs(Path en, Path docsModule) throws IOException {
        Path docsEn = docsModule.resolve("src/main/resources/en/help");
        Set<String> ours = htmlNames(en);
        Set<String> theirs = htmlNames(docsEn);
        int equal = 0;
        List<String> different = new ArrayList<>();
        for (String name : ours) {
            if (!theirs.contains(name)) {
                continue;
            }
            if (normalizedBody(en.resolve(name)).equals(normalizedBody(docsEn.resolve(name)))) {
                equal++;
            } else {
                different.add(name);
            }
        }
        Map<String, Object> result = new LinkedHashMap<>();
        result.put("docsModule", tree.root().getParent().relativize(docsModule).toString().replace('\\', '/'));
        result.put("englishPages", theirs.size());
        result.put("inBoth", equal + different.size());
        result.put("bodyEqual", equal);
        result.put("bodyDifferent", different);
        result.put("onlyInAdmingui", ours.stream().filter(n -> !theirs.contains(n)).toList());
        result.put("onlyInDocs", theirs.stream().filter(n -> !ours.contains(n)).toList());

        Map<String, Object> translations = new TreeMap<>();
        Path l10n = docs.resolve("main-docs-l10n/help").resolve(docsModule.getFileName()).resolve("src/main/resources");
        if (Files.isDirectory(l10n)) {
            for (String locale : subdirectories(l10n)) {
                Set<String> translated = htmlNames(l10n.resolve(locale).resolve("help"));
                Map<String, Object> counts = new LinkedHashMap<>();
                counts.put("pages", translated.size());
                counts.put("matchingAdminguiPages", (int) ours.stream().filter(translated::contains).count());
                translations.put(locale, counts);
            }
        }
        result.put("translatedHelp", translations);
        return result;
    }

    private Map<String, Path> docsModules() throws IOException {
        Map<String, Path> result = new TreeMap<>();
        Path help = docs.resolve("main-docs/help");
        if (!Files.isDirectory(help)) {
            return result;
        }
        try (Stream<Path> directories = Files.list(help)) {
            for (Path directory : directories.filter(Files::isDirectory).toList()) {
                String name = directory.getFileName().toString();
                result.put(DOCS_TO_ADMINGUI.getOrDefault(name, name), directory);
            }
        }
        return result;
    }

    private static String normalizedBody(Path file) throws IOException {
        String text = AdminguiTree.read(file);
        text = LEADING_COMMENT.matcher(text).replaceFirst("");
        text = COPYRIGHT_FOOTER.matcher(text).replaceAll("");
        return WHITESPACE.matcher(text).replaceAll(" ").trim();
    }

    private static List<String> targets(Path xml, String element) throws Exception {
        List<String> result = new ArrayList<>();
        if (!Files.isRegularFile(xml)) {
            return result;
        }
        NodeList items = Pom.Xml.parse(xml).getElementsByTagName(element);
        for (int i = 0; i < items.getLength(); i++) {
            String target = ((Element) items.item(i)).getAttribute("target");
            if (!target.isEmpty()) {
                result.add(target);
            }
        }
        return result;
    }

    private static List<String> supportedLocales(Path facesConfig) throws Exception {
        List<String> result = new ArrayList<>();
        Document document = Pom.Xml.parse(facesConfig);
        NodeList defaults = document.getElementsByTagName("default-locale");
        for (int i = 0; i < defaults.getLength(); i++) {
            result.add(defaults.item(i).getTextContent().trim() + " (default)");
        }
        NodeList supported = document.getElementsByTagName("supported-locale");
        for (int i = 0; i < supported.getLength(); i++) {
            result.add(supported.item(i).getTextContent().trim());
        }
        return result;
    }

    /** Help targets name a page without its extension and may carry an anchor. */
    private static String page(String target) {
        return stripAnchor(target) + ".html";
    }

    private static String stripAnchor(String reference) {
        int hash = reference.indexOf('#');
        return hash < 0 ? reference : reference.substring(0, hash);
    }

    private static List<String> missing(List<String> references, Set<String> pages) {
        return references.stream().filter(r -> !pages.contains(r)).distinct().sorted().toList();
    }

    private static Set<String> htmlNames(Path directory) throws IOException {
        Set<String> names = new TreeSet<>();
        if (Files.isDirectory(directory)) {
            try (Stream<Path> files = Files.list(directory)) {
                files.map(p -> p.getFileName().toString()).filter(n -> n.endsWith(".html")).forEach(names::add);
            }
        }
        return names;
    }

    private static List<String> subdirectories(Path directory) throws IOException {
        try (Stream<Path> children = Files.list(directory)) {
            return children.filter(Files::isDirectory).map(p -> p.getFileName().toString()).sorted().toList();
        }
    }

    private static Properties load(Path file) throws IOException {
        Properties properties = new Properties();
        try (InputStream in = Files.newInputStream(file)) {
            properties.load(in);
        }
        return properties;
    }
}
