package inventory;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Writes inventory/jsft-features.yaml (調査計画.md S3): which JSFTemplating page constructs and Java APIs each
 * admin console module uses. Counts are textual matches (comments are not excluded).
 */
final class JsftFeaturesExtractor {

    private static final Map<String, Pattern> COUNTED = counted();
    private static final Pattern JSFTEMPLATING_IMPORT = Pattern.compile("(?m)^import\\s+(com\\.sun\\.jsftemplating\\.[\\w.]+)\\s*;");

    private final AdminguiTree tree;

    JsftFeaturesExtractor(Path root) {
        this.tree = new AdminguiTree(root);
    }

    /** Each pattern's group 1 is the kind being counted; a pattern without a group counts occurrences. */
    private static Map<String, Pattern> counted() {
        Map<String, Pattern> counted = new LinkedHashMap<>();
        counted.put("specialTags", Pattern.compile("<!(?!DOCTYPE)([a-zA-Z]+)"));
        counted.put("dataSources", Pattern.compile("\\$([a-zA-Z]+)\\{"));
        counted.put("elRoots", Pattern.compile("#\\{([a-zA-Z_]\\w*)[.\\[]"));
        counted.put("tagPrefixes", Pattern.compile("<([a-zA-Z]+):[a-zA-Z]"));
        counted.put("includeDirectives", Pattern.compile("(?m)^\\s*#include\\b"));
        counted.put("pageHandlerDefinitions", Pattern.compile("<handler\\s+id="));
        counted.put("eventBlocks", Pattern.compile("<event>"));
        counted.put("uiEventBlocks", Pattern.compile("<ui:event\\b"));
        return counted;
    }

    void write(Path output) throws Exception {
        Map<String, Object> totals = emptyCounts();
        List<Object> modules = new ArrayList<>();
        for (Path module : tree.modules()) {
            Map<String, Object> counts = emptyCounts();
            int pages = 0;
            for (Path page : tree.pages(module)) {
                pages++;
                String text = AdminguiTree.read(page);
                count(text, counts);
                count(text, totals);
            }
            Map<String, Integer> imports = new TreeMap<>();
            for (Path java : tree.mainJavaSources(module)) {
                Matcher matcher = JSFTEMPLATING_IMPORT.matcher(AdminguiTree.read(java));
                while (matcher.find()) {
                    imports.merge(matcher.group(1), 1, Integer::sum);
                }
            }
            @SuppressWarnings("unchecked")
            Map<String, Integer> totalImports = (Map<String, Integer>) totals.computeIfAbsent("jsftemplatingImports", k -> new TreeMap<String, Integer>());
            imports.forEach((k, v) -> totalImports.merge(k, v, Integer::sum));

            Map<String, Object> entry = new LinkedHashMap<>();
            entry.put("module", module.getFileName().toString());
            entry.put("pages", pages);
            entry.putAll(counts);
            entry.put("jsftemplatingImports", imports);
            modules.add(entry);
        }

        Map<String, Object> document = new LinkedHashMap<>();
        Map<String, Object> source = new LinkedHashMap<>();
        source.put("repository", "glassfish");
        source.put("commit", ModulesExtractor.Git.head(tree.root()));
        document.put("source", source);
        document.put("totals", totals);
        document.put("modules", modules);

        Files.createDirectories(output.getParent());
        Files.writeString(output, Yaml.write(document,
                "Generated by tools/inventory/extractor (jsft-features). Do not edit by hand.\n"
                        + "Counts are textual matches in .jsf/.inc/.layout files (comments included).\n"
                        + "Interpretation and notes belong in docs/as-is/jsftemplating.md."),
                StandardCharsets.UTF_8);
    }

    private static Map<String, Object> emptyCounts() {
        Map<String, Object> counts = new LinkedHashMap<>();
        for (Map.Entry<String, Pattern> entry : COUNTED.entrySet()) {
            counts.put(entry.getKey(), entry.getValue().matcher("").groupCount() > 0 ? new TreeMap<String, Integer>() : 0);
        }
        return counts;
    }

    @SuppressWarnings("unchecked")
    private static void count(String text, Map<String, Object> counts) {
        for (Map.Entry<String, Pattern> entry : COUNTED.entrySet()) {
            Matcher matcher = entry.getValue().matcher(text);
            while (matcher.find()) {
                if (matcher.groupCount() > 0) {
                    ((Map<String, Integer>) counts.get(entry.getKey())).merge(matcher.group(1), 1, Integer::sum);
                } else {
                    counts.merge(entry.getKey(), 1, (a, b) -> (Integer) a + (Integer) b);
                }
            }
        }
    }
}
