package inventory;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.stream.Stream;

/** Writes inventory/modules.yaml (調査計画.md S1): admin console modules, their dependencies and contents. */
final class ModulesExtractor {

    private static final String ADMINGUI_GROUP = "org.glassfish.main.admingui";
    private static final String GLASSFISH_GROUP = "org.glassfish.main.";

    private final Path root;
    private final Path admingui;

    ModulesExtractor(Path root) {
        this.root = root;
        this.admingui = root.resolve("appserver").resolve("admingui");
    }

    void write(Path output) throws Exception {
        Map<String, Object> document = new LinkedHashMap<>();
        Map<String, Object> source = new LinkedHashMap<>();
        source.put("repository", "glassfish");
        source.put("commit", Git.head(root));
        document.put("source", source);

        Map<String, Set<String>> featuresets = featuresetsByArtifact();
        Set<String> bundledInWar = adminguiArtifacts(Pom.read(admingui.resolve("war").resolve("pom.xml")));

        List<Object> modules = new ArrayList<>();
        try (Stream<Path> directories = Files.list(admingui)) {
            for (Path directory : directories.filter(d -> Files.isRegularFile(d.resolve("pom.xml"))).sorted().toList()) {
                modules.add(module(directory, featuresets, bundledInWar));
            }
        }
        document.put("modules", modules);

        Files.createDirectories(output.getParent());
        Files.writeString(output, Yaml.write(document,
                "Generated by tools/inventory/extractor (modules). Do not edit by hand.\n"
                        + "Interpretation and notes belong in docs/as-is/modules.md."),
                StandardCharsets.UTF_8);
    }

    private Map<String, Object> module(Path directory, Map<String, Set<String>> featuresets, Set<String> bundledInWar)
            throws Exception {
        Pom pom = Pom.read(directory.resolve("pom.xml"));
        Map<String, Object> module = new LinkedHashMap<>();
        module.put("directory", relative(directory));
        module.put("artifactId", pom.artifactId());
        module.put("packaging", pom.packaging());
        module.put("consoleConfigId", consoleConfigId(directory));
        module.put("featuresets", new ArrayList<>(featuresets.getOrDefault(pom.artifactId(), Set.of())));
        module.put("bundledInAdminguiWar", bundledInWar.contains(pom.artifactId()));
        module.put("dependencies", dependencies(pom));
        module.put("files", fileCounts(directory));
        return module;
    }

    /** Featureset directory names that declare each admin console artifact as a dependency. */
    private Map<String, Set<String>> featuresetsByArtifact() throws Exception {
        Map<String, Set<String>> result = new TreeMap<>();
        Path featuresets = root.resolve("appserver").resolve("featuresets");
        try (Stream<Path> directories = Files.list(featuresets)) {
            for (Path directory : directories.filter(d -> Files.isRegularFile(d.resolve("pom.xml"))).sorted().toList()) {
                for (String artifactId : adminguiArtifacts(Pom.read(directory.resolve("pom.xml")))) {
                    result.computeIfAbsent(artifactId, k -> new TreeSet<>()).add(directory.getFileName().toString());
                }
            }
        }
        return result;
    }

    private static Set<String> adminguiArtifacts(Pom pom) {
        Set<String> result = new TreeSet<>();
        for (Pom.Dependency dependency : pom.dependencies()) {
            if (dependency.groupId() != null && dependency.groupId().startsWith(ADMINGUI_GROUP)) {
                result.add(dependency.artifactId());
            }
        }
        return result;
    }

    private static Map<String, Object> dependencies(Pom pom) {
        Set<String> admingui = new TreeSet<>();
        Set<String> glassfish = new TreeSet<>();
        Set<String> external = new TreeSet<>();
        for (Pom.Dependency dependency : pom.dependencies()) {
            String groupId = String.valueOf(dependency.groupId());
            String scope = dependency.scope() == null || "compile".equals(dependency.scope()) ? "" : " (" + dependency.scope() + ")";
            if (groupId.startsWith(ADMINGUI_GROUP)) {
                admingui.add(dependency.artifactId() + scope);
            } else if (groupId.startsWith(GLASSFISH_GROUP)) {
                glassfish.add(groupId.substring(GLASSFISH_GROUP.length()) + ":" + dependency.artifactId() + scope);
            } else {
                external.add(groupId + ":" + dependency.artifactId() + scope);
            }
        }
        Map<String, Object> result = new LinkedHashMap<>();
        result.put("admingui", new ArrayList<>(admingui));
        result.put("glassfish", new ArrayList<>(glassfish));
        result.put("external", new ArrayList<>(external));
        return result;
    }

    private static String consoleConfigId(Path directory) throws Exception {
        Path config = directory.resolve("src/main/resources/META-INF/admingui/console-config.xml");
        if (!Files.isRegularFile(config)) {
            return null;
        }
        String id = Pom.Xml.parse(config).getDocumentElement().getAttribute("id");
        return id.isEmpty() ? null : id;
    }

    private Map<String, Object> fileCounts(Path directory) throws IOException {
        Map<String, Integer> counts = new LinkedHashMap<>();
        for (String key : List.of("jsf", "inc", "layout", "xhtml", "javaMain", "javaTest", "helpHtml", "properties")) {
            counts.put(key, 0);
        }
        Path src = directory.resolve("src");
        if (Files.isDirectory(src)) {
            try (Stream<Path> files = Files.walk(src)) {
                for (Path file : files.filter(Files::isRegularFile).toList()) {
                    String path = src.relativize(file).toString().replace('\\', '/');
                    String name = file.getFileName().toString();
                    if (name.endsWith(".jsf")) {
                        counts.merge("jsf", 1, Integer::sum);
                    } else if (name.endsWith(".inc")) {
                        counts.merge("inc", 1, Integer::sum);
                    } else if (name.endsWith(".layout")) {
                        counts.merge("layout", 1, Integer::sum);
                    } else if (name.endsWith(".xhtml")) {
                        counts.merge("xhtml", 1, Integer::sum);
                    } else if (name.endsWith(".java") && path.startsWith("main/java/")) {
                        counts.merge("javaMain", 1, Integer::sum);
                    } else if (name.endsWith(".java") && path.startsWith("test/java/")) {
                        counts.merge("javaTest", 1, Integer::sum);
                    } else if (name.endsWith(".html") && path.startsWith("main/help/")) {
                        counts.merge("helpHtml", 1, Integer::sum);
                    } else if (name.endsWith(".properties")) {
                        counts.merge("properties", 1, Integer::sum);
                    }
                }
            }
        }
        return new LinkedHashMap<>(counts);
    }

    private String relative(Path path) {
        return root.relativize(path).toString().replace('\\', '/');
    }

    /** Reads the checked-out commit with the git command line. */
    static final class Git {

        private Git() {
        }

        static String head(Path repository) {
            try {
                Process process = new ProcessBuilder("git", "-C", repository.toString(), "rev-parse", "HEAD")
                        .redirectErrorStream(true).start();
                String out = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8).trim();
                return process.waitFor() == 0 ? out : "unknown";
            } catch (IOException e) {
                return "unknown";
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                return "unknown";
            }
        }
    }
}
