package inventory;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Writes inventory/operations.yaml (調査計画.md S5): management REST calls made by the admin console, grouped into
 * operations (HTTP method and endpoint template), with the screens they are made from and the events they run in.
 *
 * <p>Everything is textual. Page calls are calls of handlers that take an endpoint input. Endpoints are normalized:
 * {@code #{sessionScope.REST_URL}} becomes {@code {REST}}; a page session or request attribute is expanded when
 * exactly one value is assigned to it in the files that make up the same screen; any other expression becomes
 * {@code {name}}. A file belongs to the screens that include it or use it as their template.
 *
 * <p>HTTP methods: RestUtil's own methods are resolved first, down to its request primitives. A handler's methods
 * come from the RestUtil calls in the handler method and in the methods of the same class it calls (two levels).
 * Helpers in other classes than RestUtil are not followed.
 */
final class OperationsExtractor {

    private static final Set<String> ENDPOINT_INPUTS = Set.of("endpoint", "parentEndpoint", "endPoint");
    private static final int CONTAINER_DEPTH = 3;
    private static final int EXPANSION_ROUNDS = 3;
    private static final int HELPER_DEPTH = 2;
    private static final int REST_UTIL_DEPTH = 4;

    /** RestUtil's request primitives and the HTTP method each one sends (restRequest takes it as an argument). */
    private static final Map<String, String> PRIMITIVES = Map.of(
            "get", "GET", "post", "POST", "put", "PUT", "delete", "DELETE", "options", "OPTIONS", "restRequest", "(argument)");
    private static final Set<String> READ_ONLY = Set.of("GET", "OPTIONS");
    private static final String INPUT_METHOD = "(input method)";
    private static final String REST_UTIL_IMPORT = "import static org.glassfish.admingui.common.util.RestUtil.";

    private static final Pattern EVENT_START = Pattern.compile("<!(initPage|beforeCreate|afterCreate|beforeEncode|command|filterTree)\\b|<ui:event\\s+type=\"([a-zA-Z]+)\"|<(handler)\\s+id=\"");
    private static final Pattern ATTRIBUTE = Pattern.compile("([A-Za-z_][\\w]*)\\s*=\\s*\"([^\"]*)\"");
    private static final Pattern ASSIGNMENT = Pattern.compile("set(?:PageSession)?Attribute\\(\\s*key=\"([A-Za-z_][\\w]*)\"\\s*,?\\s*value=\"([^\"]*)\"");
    private static final Pattern SCOPED_VARIABLE = Pattern.compile("#\\{(?:pageSession|requestScope)\\.([A-Za-z_][\\w]*)\\}|\\$(?:pageSession|attribute)\\{([A-Za-z_][\\w]*)\\}");
    private static final Pattern ANY_EXPRESSION = Pattern.compile("#\\{([^}]*)\\}|\\$[a-zA-Z]+\\{([^}]*)\\}");

    /** A method declaration up to the opening parenthesis: at least one modifier, a return type, the name. */
    private static final Pattern METHOD_DECLARATION = Pattern.compile(
            "(?m)^[ \\t]*(?:(?:public|private|protected|static|final|synchronized)\\s+)+[\\w<>\\[\\],.? ]+?\\s+(\\w+)\\s*\\(");
    private static final Pattern LOCAL_CALL = Pattern.compile("(?<![\\w.])(\\w+)\\s*\\(");
    /** A request sent directly through a JAX-RS invocation builder, e.g. {@code .post(Entity.entity(...), Response.class)}. */
    private static final Pattern JERSEY_INVOCATION = Pattern.compile("\\.\\s*(get|post|put|delete|options)\\s*\\(\\s*(?:Response\\.class|Entity\\.)");
    private static final Pattern STRING_LITERAL = Pattern.compile("\"((?:[^\"\\\\]|\\\\.)*)\"");
    private static final Pattern HANDLER_ANNOTATION = Pattern.compile("@Handler\\s*\\(\\s*id\\s*=\\s*\"([^\"]+)\"");
    private static final Pattern NON_REST_MANAGEMENT = Pattern.compile("^import\\s+(javax\\.management\\.[\\w.]+|org\\.glassfish\\.hk2\\.api\\.ServiceLocator|com\\.sun\\.enterprise\\.config\\.serverbeans\\.[\\w.]+)\\s*;", Pattern.MULTILINE);

    private record JavaMethod(String name, String handler, int bodyStart, int bodyEnd) {
    }

    private final AdminguiTree tree;
    private PageIndex index;
    /** HTTP methods sent by each RestUtil method (primitives excluded). */
    private final Map<String, Set<String>> restUtilMethods = new TreeMap<>();

    OperationsExtractor(Path root) {
        this.tree = new AdminguiTree(root);
    }

    void write(Path output) throws Exception {
        Map<String, Object> document = build();
        Files.createDirectories(output.getParent());
        Files.writeString(output, Yaml.write(document,
                "Generated by tools/inventory/extractor (operations). Do not edit by hand.\n"
                        + "Textual extraction: endpoints are templates, {REST} is the REST base URL, {name} is an unexpanded value.\n"
                        + "Interpretation and notes belong in docs/as-is/rest-bridge.md."),
                StandardCharsets.UTF_8);
    }

    /** The inventory document; {@code operations} holds maps with {@code screens} and {@code stateChanging}. */
    Map<String, Object> build() throws Exception {
        index = PageIndex.load(tree);
        Map<String, HandlerDefinitions.Definition> definitions = new TreeMap<>();
        for (HandlerDefinitions.Definition definition : HandlerDefinitions.read(tree)) {
            definitions.putIfAbsent(definition.id(), definition);
        }

        List<Path> javaSources = new ArrayList<>();
        for (Path module : tree.modules()) {
            javaSources.addAll(tree.mainJavaSources(module));
        }
        for (Path java : javaSources) {
            if (java.getFileName().toString().equals("RestUtil.java")) {
                analyzeRestUtil(AdminguiTree.read(java));
            }
        }
        List<Map<String, Object>> javaCallSites = new ArrayList<>();
        Map<String, Set<String>> javaMethodsByHandler = new TreeMap<>();
        Map<String, List<String>> nonRest = new TreeMap<>();
        for (Path java : javaSources) {
            scanJava(java, javaCallSites, javaMethodsByHandler, nonRest);
        }

        Map<String, String> endpointInputByHandler = new TreeMap<>();
        definitions.values().forEach(d -> d.inputs().stream()
                .filter(io -> ENDPOINT_INPUTS.contains(io.name()))
                .findFirst()
                .ifPresent(io -> endpointInputByHandler.put(d.id(), io.name())));
        Pattern pageCall = Pattern.compile("(?<![\\w.$#{])(" + String.join("|",
                endpointInputByHandler.keySet().stream().map(Pattern::quote).toList()) + ")\\s*\\(");

        Map<String, Map<String, Object>> operations = new TreeMap<>();
        Map<String, Integer> callsByHandler = new TreeMap<>();
        Map<String, Integer> callsByMethod = new TreeMap<>();
        int calls = 0;
        int stateChangingCalls = 0;
        int unknownBaseCalls = 0;
        for (PageIndex.Page page : index.pages()) {
            Map<String, Set<String>> assignments = null;
            Matcher call = pageCall.matcher(page.text());
            while (call.find()) {
                String handlerId = call.group(1);
                String arguments = arguments(page.text(), call.end() - 1);
                if (arguments == null) {
                    continue;
                }
                Map<String, String> attributes = attributes(arguments);
                String rawEndpoint = attributes.get(endpointInputByHandler.get(handlerId));
                if (rawEndpoint == null) {
                    continue;
                }
                if (assignments == null) {
                    assignments = assignments(index.screenScope(page.url(), CONTAINER_DEPTH));
                }
                String endpoint = normalizeEndpoint(expand(rawEndpoint, assignments));
                Set<String> methods = httpMethods(attributes, definitions.get(handlerId), javaMethodsByHandler.getOrDefault(handlerId, Set.of()));
                String event = event(page.text(), call.start());
                boolean stateChanging = methods.stream().anyMatch(m -> !READ_ONLY.contains(m));

                calls++;
                callsByHandler.merge(handlerId, 1, Integer::sum);
                methods.forEach(m -> callsByMethod.merge(m, 1, Integer::sum));
                if (stateChanging) {
                    stateChangingCalls++;
                }
                if (!endpoint.startsWith("{REST}")) {
                    unknownBaseCalls++;
                }

                String key = String.join("|", methods) + " " + endpoint;
                Map<String, Object> operation = operations.computeIfAbsent(key, k -> newOperation(methods, endpoint));
                operation.put("calls", (int) operation.get("calls") + 1);
                operation.put("stateChanging", (boolean) operation.get("stateChanging") || stateChanging);
                addTo(operation, "handlers", handlerId);
                increment(operation, "events", event);
                addTo(operation, "sources", page.source());
                index.screens(page.url(), CONTAINER_DEPTH).forEach(s -> addTo(operation, "screens", s));
            }
        }

        List<Object> operationList = new ArrayList<>();
        int stateChangingOperations = 0;
        List<String> stateChangingWithoutScreen = new ArrayList<>();
        for (Map<String, Object> operation : operations.values()) {
            finish(operation);
            if ((boolean) operation.get("stateChanging")) {
                stateChangingOperations++;
                if (((List<?>) operation.get("screens")).isEmpty()) {
                    stateChangingWithoutScreen.add(operation.get("httpMethods") + " " + operation.get("endpoint"));
                }
            }
            operationList.add(operation);
        }

        Map<String, Object> summary = new LinkedHashMap<>();
        summary.put("pageCalls", calls);
        summary.put("stateChangingPageCalls", stateChangingCalls);
        summary.put("pageCallsWithUnknownBaseUrl", unknownBaseCalls);
        summary.put("callsByHandler", callsByHandler);
        summary.put("callsByHttpMethod", callsByMethod);
        summary.put("operations", operations.size());
        summary.put("stateChangingOperations", stateChangingOperations);
        summary.put("stateChangingOperationsWithoutScreen", stateChangingWithoutScreen);
        summary.put("javaRestCallSites", javaCallSites.size());
        summary.put("javaFilesUsingNonRestManagementApis", nonRest.size());

        Map<String, Object> restUtil = new TreeMap<>();
        restUtilMethods.forEach((name, methods) -> restUtil.put(name, new ArrayList<>(methods)));
        Map<String, Object> handlerMethods = new TreeMap<>();
        javaMethodsByHandler.forEach((id, methods) -> handlerMethods.put(id, new ArrayList<>(methods)));

        Map<String, Object> document = new LinkedHashMap<>();
        Map<String, Object> source = new LinkedHashMap<>();
        source.put("repository", "glassfish");
        source.put("commit", ModulesExtractor.Git.head(tree.root()));
        document.put("source", source);
        document.put("summary", summary);
        document.put("httpMethodsByRestUtilMethod", restUtil);
        document.put("httpMethodsByHandler", handlerMethods);
        document.put("nonRestManagementApis", nonRest);
        document.put("operations", operationList);
        document.put("javaRestCallSites", javaCallSites);
        return document;
    }

    /** Values assigned to each attribute name in the given files. */
    private Map<String, Set<String>> assignments(Set<String> files) {
        Map<String, Set<String>> result = new TreeMap<>();
        for (String url : files) {
            Matcher assignment = ASSIGNMENT.matcher(index.page(url).text());
            while (assignment.find()) {
                result.computeIfAbsent(assignment.group(1), k -> new TreeSet<>()).add(assignment.group(2));
            }
        }
        return result;
    }

    /** The text between the parentheses starting at {@code open}, honoring double quotes; null if unbalanced. */
    static String arguments(String text, int open) {
        boolean quoted = false;
        int depth = 0;
        for (int i = open; i < text.length(); i++) {
            char c = text.charAt(i);
            if (c == '\\' && quoted) {
                i++;
            } else if (c == '"') {
                quoted = !quoted;
            } else if (!quoted && c == '(') {
                depth++;
            } else if (!quoted && c == ')' && --depth == 0) {
                return text.substring(open + 1, i);
            }
        }
        return null;
    }

    /** Handler call attributes ({@code name="value"}), first occurrence wins. */
    static Map<String, String> attributes(String arguments) {
        Map<String, String> result = new LinkedHashMap<>();
        Matcher attribute = ATTRIBUTE.matcher(arguments);
        while (attribute.find()) {
            result.putIfAbsent(attribute.group(1), attribute.group(2));
        }
        return result;
    }

    private static String expand(String endpoint, Map<String, Set<String>> assignments) {
        String current = endpoint;
        for (int round = 0; round < EXPANSION_ROUNDS; round++) {
            Matcher variable = SCOPED_VARIABLE.matcher(current);
            StringBuilder sb = new StringBuilder();
            boolean changed = false;
            while (variable.find()) {
                String name = variable.group(1) != null ? variable.group(1) : variable.group(2);
                Set<String> values = assignments.get(name);
                String replacement = variable.group();
                if (values != null && values.size() == 1) {
                    String value = values.iterator().next();
                    if (!value.contains(variable.group())) {
                        replacement = value;
                        changed = true;
                    }
                }
                variable.appendReplacement(sb, Matcher.quoteReplacement(replacement));
            }
            variable.appendTail(sb);
            current = sb.toString();
            if (!changed) {
                break;
            }
        }
        return current;
    }

    static String normalizeEndpoint(String endpoint) {
        String result = endpoint.replace("#{sessionScope.REST_URL}", "{REST}");
        Matcher expression = ANY_EXPRESSION.matcher(result);
        StringBuilder sb = new StringBuilder();
        while (expression.find()) {
            String inner = expression.group(1) != null ? expression.group(1) : expression.group(2);
            String name = inner.contains(".") ? inner.substring(inner.lastIndexOf('.') + 1) : inner;
            expression.appendReplacement(sb, Matcher.quoteReplacement("{" + name.trim() + "}"));
        }
        expression.appendTail(sb);
        result = sb.toString();
        int query = result.indexOf('?');
        return query < 0 ? result : result.substring(0, query);
    }

    /** HTTP methods of a page call: the handler's methods, with a passed-through method input taken from the call. */
    private static Set<String> httpMethods(Map<String, String> attributes, HandlerDefinitions.Definition definition, Set<String> fromJava) {
        Set<String> methods = new TreeSet<>();
        if (fromJava.contains(INPUT_METHOD)) {
            String method = attributes.get("method");
            if (method == null && definition != null) {
                method = definition.inputs().stream().filter(io -> io.name().equals("method"))
                        .map(HandlerDefinitions.Io::defaultValue).filter(v -> v != null).findFirst().orElse(null);
            }
            methods.add(method == null ? "UNKNOWN" : method.toUpperCase());
        }
        fromJava.stream().filter(m -> !m.startsWith("(")).forEach(methods::add);
        if (methods.isEmpty()) {
            methods.add("UNKNOWN");
        }
        return methods;
    }

    /** The JSFTemplating event the call is inside, or "none". */
    /** The event block ({@code beforeCreate}, {@code command}, ...) that contains the position, or {@code none}. */
    static String event(String text, int position) {
        Matcher start = EVENT_START.matcher(text);
        String event = "none";
        int eventStart = -1;
        while (start.find() && start.start() < position) {
            event = start.group(1) != null ? start.group(1) : start.group(2) != null ? start.group(2) : "pageDefinedHandler";
            eventStart = start.start();
        }
        if (eventStart < 0) {
            return "none";
        }
        String between = text.substring(eventStart, position);
        boolean closed;
        if (text.startsWith("<ui:event", eventStart)) {
            closed = between.contains("</ui:event>");
        } else if (text.startsWith("<handler", eventStart)) {
            closed = between.contains("</handler>");
        } else {
            closed = between.matches("(?s).*\\n\\s*/>.*");
        }
        return closed ? "none" : event;
    }

    /** Resolves the HTTP methods of each RestUtil method from the primitives it calls, directly or through other RestUtil methods. */
    private void analyzeRestUtil(String text) {
        List<JavaMethod> methods = methods(text);
        Map<String, Set<String>> direct = new TreeMap<>();
        Map<String, Set<String>> callees = new TreeMap<>();
        Set<String> names = new TreeSet<>();
        methods.forEach(m -> names.add(m.name()));
        for (JavaMethod method : methods) {
            if (PRIMITIVES.containsKey(method.name())) {
                continue;
            }
            String body = text.substring(method.bodyStart(), method.bodyEnd());
            Matcher local = LOCAL_CALL.matcher(body);
            while (local.find()) {
                String name = local.group(1);
                if (PRIMITIVES.containsKey(name)) {
                    direct.computeIfAbsent(method.name(), k -> new TreeSet<>()).add(primitiveMethod(name, arguments(body, local.end() - 1)));
                } else if (names.contains(name) && !name.equals(method.name())) {
                    callees.computeIfAbsent(method.name(), k -> new TreeSet<>()).add(name);
                }
            }
            Matcher invocation = JERSEY_INVOCATION.matcher(body);
            while (invocation.find()) {
                direct.computeIfAbsent(method.name(), k -> new TreeSet<>()).add(invocation.group(1).toUpperCase());
            }
        }
        for (String name : names) {
            if (PRIMITIVES.containsKey(name)) {
                continue;
            }
            Set<String> resolved = new TreeSet<>();
            resolveRestUtil(name, direct, callees, REST_UTIL_DEPTH, new TreeSet<>(), resolved);
            if (!resolved.isEmpty()) {
                restUtilMethods.put(name, resolved);
            }
        }
    }

    private static void resolveRestUtil(String name, Map<String, Set<String>> direct, Map<String, Set<String>> callees, int depth,
            Set<String> visited, Set<String> resolved) {
        if (!visited.add(name)) {
            return;
        }
        resolved.addAll(direct.getOrDefault(name, Set.of()));
        if (depth > 0) {
            callees.getOrDefault(name, Set.of()).forEach(c -> resolveRestUtil(c, direct, callees, depth - 1, visited, resolved));
        }
    }

    private void scanJava(Path java, List<Map<String, Object>> callSites, Map<String, Set<String>> methodsByHandler,
            Map<String, List<String>> nonRest) throws Exception {
        String text = AdminguiTree.read(java);
        String relative = tree.relative(java);
        Matcher management = NON_REST_MANAGEMENT.matcher(text);
        Set<String> apis = new TreeSet<>();
        while (management.find()) {
            apis.add(management.group(1));
        }
        if (!apis.isEmpty()) {
            nonRest.put(relative, new ArrayList<>(apis));
        }
        if (java.getFileName().toString().equals("RestUtil.java")) {
            return;
        }

        Set<String> restNames = new TreeSet<>(PRIMITIVES.keySet());
        restNames.addAll(restUtilMethods.keySet());
        Pattern restCall = Pattern.compile("(?<![\\w.])(?:(RestUtil)\\.)?(" + String.join("|", restNames) + ")\\s*\\(");

        List<JavaMethod> methods = methods(text);
        Map<String, Set<String>> directByMethod = new TreeMap<>();
        Matcher call = restCall.matcher(text);
        while (call.find()) {
            boolean qualified = call.group(1) != null;
            String name = call.group(2);
            if (inLineComment(text, call.start()) || (!qualified && !importedStatically(text, name))) {
                continue;
            }
            JavaMethod enclosing = enclosing(methods, call.start());
            if (enclosing == null) {
                continue;
            }
            String arguments = arguments(text, call.end() - 1);
            Set<String> httpMethods = PRIMITIVES.containsKey(name)
                    ? Set.of(primitiveMethod(name, arguments))
                    : restUtilMethods.get(name);
            directByMethod.computeIfAbsent(enclosing.name(), k -> new TreeSet<>()).addAll(httpMethods);
            callSites.add(callSite(relative, text, call.start(), enclosing, (qualified ? "RestUtil." : "") + name, httpMethods,
                    endpointLiterals(text, call.start(), arguments)));
        }
        Matcher invocation = JERSEY_INVOCATION.matcher(text);
        while (invocation.find()) {
            JavaMethod enclosing = enclosing(methods, invocation.start());
            if (enclosing == null || inLineComment(text, invocation.start())) {
                continue;
            }
            Set<String> httpMethods = Set.of(invocation.group(1).toUpperCase());
            directByMethod.computeIfAbsent(enclosing.name(), k -> new TreeSet<>()).addAll(httpMethods);
            callSites.add(callSite(relative, text, invocation.start(), enclosing, "(JAX-RS client)." + invocation.group(1), httpMethods, List.of()));
        }

        Set<String> names = new TreeSet<>();
        methods.forEach(m -> names.add(m.name()));
        for (JavaMethod method : methods) {
            if (method.handler() == null) {
                continue;
            }
            Set<String> reached = new TreeSet<>();
            collectHttpMethods(text, methods, names, directByMethod, method, HELPER_DEPTH, new TreeSet<>(), reached);
            if (!reached.isEmpty()) {
                methodsByHandler.computeIfAbsent(method.handler(), k -> new TreeSet<>()).addAll(reached);
            }
        }
    }

    private static Map<String, Object> callSite(String file, String text, int position, JavaMethod enclosing, String call,
            Set<String> httpMethods, List<String> endpointLiterals) {
        Map<String, Object> site = new LinkedHashMap<>();
        site.put("file", file);
        site.put("line", lineOf(text, position));
        site.put("method", enclosing.name());
        site.put("handler", enclosing.handler());
        site.put("call", call);
        site.put("httpMethods", new ArrayList<>(new TreeSet<>(httpMethods)));
        site.put("endpointLiterals", endpointLiterals);
        return site;
    }

    /** Whether the position follows {@code //} or a leading {@code *} on its line (block comments are not tracked further). */
    private static boolean inLineComment(String text, int position) {
        String before = text.substring(text.lastIndexOf('\n', position - 1) + 1, position);
        return before.contains("//") || before.stripLeading().startsWith("*");
    }

    private static boolean importedStatically(String text, String name) {
        return text.contains(REST_UTIL_IMPORT + name + ";") || text.contains(REST_UTIL_IMPORT + "*;");
    }

    private static void collectHttpMethods(String text, List<JavaMethod> methods, Set<String> names, Map<String, Set<String>> direct,
            JavaMethod method, int depth, Set<String> visited, Set<String> reached) {
        if (!visited.add(method.name())) {
            return;
        }
        reached.addAll(direct.getOrDefault(method.name(), Set.of()));
        if (depth == 0) {
            return;
        }
        Matcher local = LOCAL_CALL.matcher(text.substring(method.bodyStart(), method.bodyEnd()));
        while (local.find()) {
            String name = local.group(1);
            if (!names.contains(name)) {
                continue;
            }
            for (JavaMethod callee : methods) {
                if (callee.name().equals(name) && callee.handler() == null) {
                    collectHttpMethods(text, methods, names, direct, callee, depth - 1, visited, reached);
                }
            }
        }
    }

    /** Method declarations with bodies, each with the id of the @Handler annotation directly before it. */
    private static List<JavaMethod> methods(String text) {
        List<JavaMethod> result = new ArrayList<>();
        Matcher declaration = METHOD_DECLARATION.matcher(text);
        int previousEnd = 0;
        while (declaration.find()) {
            int open = text.indexOf('{', declaration.end());
            int semicolon = text.indexOf(';', declaration.end());
            if (open < 0 || (semicolon >= 0 && semicolon < open)) {
                continue;
            }
            String body = JavaSource.blockAfter(text, declaration.end());
            if (body == null) {
                continue;
            }
            String handler = null;
            Matcher annotation = HANDLER_ANNOTATION.matcher(text.substring(Math.min(previousEnd, declaration.start()), declaration.start()));
            while (annotation.find()) {
                handler = annotation.group(1);
            }
            int bodyEnd = open + body.length();
            result.add(new JavaMethod(declaration.group(1), handler, open, bodyEnd));
            previousEnd = bodyEnd;
        }
        return result;
    }

    /** The innermost method whose body contains the position. */
    private static JavaMethod enclosing(List<JavaMethod> methods, int position) {
        JavaMethod result = null;
        for (JavaMethod method : methods) {
            if (method.bodyStart() < position && position < method.bodyEnd()
                    && (result == null || method.bodyStart() > result.bodyStart())) {
                result = method;
            }
        }
        return result;
    }

    /** The HTTP method a primitive call sends; for restRequest, a literal argument or a passed-through method input. */
    private static String primitiveMethod(String name, String arguments) {
        String fixed = PRIMITIVES.get(name);
        if (!fixed.startsWith("(")) {
            return fixed;
        }
        if (arguments != null) {
            Matcher literal = STRING_LITERAL.matcher(arguments);
            while (literal.find()) {
                String value = literal.group(1).toUpperCase();
                if (Set.of("GET", "POST", "PUT", "DELETE").contains(value)) {
                    return value;
                }
            }
            if (arguments.matches("(?s).*\\bmethod\\b.*")) {
                return INPUT_METHOD;
            }
        }
        return "(unknown)";
    }

    /** String literals of the call's first argument and of the last assignment to it in the preceding text. */
    private static List<String> endpointLiterals(String text, int position, String arguments) {
        List<String> literals = new ArrayList<>();
        if (arguments == null) {
            return literals;
        }
        String first = arguments.split(",", 2)[0].trim();
        if (first.matches("[A-Za-z_]\\w*")) {
            int from = Math.max(0, position - 2000);
            Matcher assignment = Pattern.compile("\\b" + Pattern.quote(first) + "\\s*=\\s*([^;]+);").matcher(text.substring(from, position));
            String last = null;
            while (assignment.find()) {
                last = assignment.group(1);
            }
            if (last != null) {
                addLiterals(last, literals);
            }
        }
        addLiterals(arguments.split(",", 2)[0], literals);
        return literals;
    }

    private static void addLiterals(String text, List<String> literals) {
        Matcher literal = STRING_LITERAL.matcher(text);
        while (literal.find()) {
            if (!literal.group(1).isEmpty() && !literals.contains(literal.group(1))) {
                literals.add(literal.group(1));
            }
        }
    }

    private static int lineOf(String text, int position) {
        int line = 1;
        for (int i = 0; i < position; i++) {
            if (text.charAt(i) == '\n') {
                line++;
            }
        }
        return line;
    }

    private static Map<String, Object> newOperation(Set<String> methods, String endpoint) {
        Map<String, Object> operation = new LinkedHashMap<>();
        operation.put("httpMethods", new ArrayList<>(methods));
        operation.put("endpoint", endpoint);
        operation.put("stateChanging", false);
        operation.put("calls", 0);
        operation.put("handlers", new TreeSet<String>());
        operation.put("events", new TreeMap<String, Integer>());
        operation.put("screens", new TreeSet<String>());
        operation.put("sources", new TreeSet<String>());
        return operation;
    }

    @SuppressWarnings("unchecked")
    private static void addTo(Map<String, Object> operation, String key, String value) {
        ((Set<String>) operation.get(key)).add(value);
    }

    @SuppressWarnings("unchecked")
    private static void increment(Map<String, Object> operation, String key, String value) {
        ((Map<String, Integer>) operation.get(key)).merge(value, 1, Integer::sum);
    }

    @SuppressWarnings("unchecked")
    private static void finish(Map<String, Object> operation) {
        for (String key : List.of("handlers", "screens", "sources")) {
            operation.put(key, new ArrayList<>((Set<String>) operation.get(key)));
        }
    }
}
