package inventory;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.regex.MatchResult;
import java.util.regex.Pattern;

/**
 * Migration worksheets (adr/0008 decision 2): for each given JSFTemplating page, a Markdown checklist of what the
 * Facelets rewrite has to cover. The worksheet lists the includes, components, event handlers, page session keys,
 * resource bundle keys and admin REST endpoints of the page. It does not generate code.
 *
 * <p>Textual extraction, like the other inventories: the page and the files it includes or uses as template are read
 * as text.
 */
final class WorksheetExtractor {

    private static final Pattern COMPONENT = Pattern.compile("<([a-zA-Z]+):([a-zA-Z]+)\\b((?:[^>\"]|\"[^\"]*\")*)>");
    private static final Pattern ATTRIBUTE_NAME = Pattern.compile("([A-Za-z_][\\w.]*)\\s*=\\s*\"");
    private static final Pattern PAGE_HANDLER = Pattern.compile("<handler\\s+id=\"([^\"]+)\"");
    private static final Pattern PAGE_SESSION_READ = Pattern.compile("#\\{pageSession\\.([A-Za-z_]\\w*)|\\$pageSession\\{([A-Za-z_]\\w*)\\}");
    private static final Pattern PAGE_SESSION_WRITE = Pattern.compile("setPageSessionAttribute\\(\\s*key=\"([A-Za-z_]\\w*)\"");
    private static final Pattern BUNDLE = Pattern.compile("setResourceBundle\\(\\s*key=\"([A-Za-z_]\\w*)\"\\s*,?\\s*bundle=\"([^\"]+)\"");
    private static final Pattern RESOURCE_KEY = Pattern.compile("\\$resource\\{([A-Za-z_]\\w*)\\.([^},]+)");

    private record HandlerCall(String event, String handler, String file) {
    }

    private final AdminguiTree tree;
    private final Path root;

    WorksheetExtractor(Path root) {
        this.root = root;
        this.tree = new AdminguiTree(root);
    }

    /** Writes {@code <output>/<module>/<page file name>.md} for each page, given relative to {@code appserver/admingui}. */
    void write(Path output, List<String> pageFiles) throws Exception {
        PageIndex index = PageIndex.load(tree);
        Set<String> handlerIds = new TreeSet<>();
        Set<String> adminguiIds = new TreeSet<>();
        for (HandlerDefinitions.Definition definition : HandlerDefinitions.read(tree)) {
            handlerIds.add(definition.id());
            if (definition.origin().equals("admingui")) {
                adminguiIds.add(definition.id());
            }
        }
        Set<String> builtinIds = new TreeSet<>(handlerIds);
        builtinIds.removeAll(adminguiIds);
        List<Map<String, Object>> operations = operations();
        for (String pageFile : pageFiles) {
            PageIndex.Page page = index.pages().stream()
                    .filter(p -> p.source().replace('\\', '/').endsWith("/" + pageFile))
                    .findFirst()
                    .orElseThrow(() -> new IllegalArgumentException("No page file " + pageFile));
            String worksheet = worksheet(index, page, handlerIds, builtinIds, operations);
            String name = pageFile.substring(pageFile.lastIndexOf('/') + 1);
            Path file = output.resolve(page.module()).resolve(name + ".md");
            Files.createDirectories(file.getParent());
            Files.writeString(file, worksheet, StandardCharsets.UTF_8);
            System.out.println("wrote " + file);
        }
    }

    @SuppressWarnings("unchecked")
    private List<Map<String, Object>> operations() throws Exception {
        Map<String, Object> document = new OperationsExtractor(root).build();
        return (List<Map<String, Object>>) (List<?>) document.get("operations");
    }

    private String worksheet(PageIndex index, PageIndex.Page page, Set<String> knownHandlers, Set<String> builtinHandlers,
            List<Map<String, Object>> operations) {
        Set<String> files = new LinkedHashSet<>(index.withIncludes(page.url()));
        files.addAll(index.composition(page.url()));
        Set<String> pageHandlers = new TreeSet<>();
        files.forEach(url -> matches(PAGE_HANDLER, index.page(url).text()).forEach(m -> pageHandlers.add(m.group(1))));
        Set<String> handlers = new TreeSet<>(knownHandlers);
        handlers.addAll(pageHandlers);
        Pattern handlerCall = Pattern.compile("(?<![\\w.$#{])(" + String.join("|", handlers.stream().map(Pattern::quote).toList()) + ")\\s*\\(");

        StringBuilder md = new StringBuilder();
        md.append("# Migration worksheet: ").append(page.url()).append("\n\n");
        md.append("Generated by tools/inventory/extractor (worksheet), commit ").append(ModulesExtractor.Git.head(root))
                .append(". Textual extraction; check each item against the page while rewriting (adr/0008).\n\n");
        md.append("- Page: `").append(page.url()).append("`\n");
        md.append("- File: `").append(page.source().replace('\\', '/')).append("`\n\n");

        md.append("## Includes\n\n");
        StringBuilder includeTree = new StringBuilder();
        includeTree(index, page.url(), 0, new LinkedHashSet<>(), includeTree);
        md.append(includeTree.length() == 0 ? "None.\n" : includeTree).append("\n");
        List<String> otherFiles = files.stream().filter(url -> !index.withIncludes(page.url()).contains(url)).toList();
        if (!otherFiles.isEmpty()) {
            md.append("Template and its includes:\n\n");
            otherFiles.forEach(url -> md.append("- `").append(url).append("`\n"));
            md.append("\n");
        }

        md.append("## Components\n\n| Component | Count | Attributes |\n| --- | --- | --- |\n");
        Map<String, Integer> componentCounts = new TreeMap<>();
        Map<String, Set<String>> componentAttributes = new TreeMap<>();
        for (String url : files) {
            for (MatchResult component : matches(COMPONENT, index.page(url).text())) {
                String name = component.group(1) + ":" + component.group(2);
                componentCounts.merge(name, 1, Integer::sum);
                Set<String> attributes = componentAttributes.computeIfAbsent(name, k -> new TreeSet<>());
                matches(ATTRIBUTE_NAME, component.group(3)).forEach(a -> attributes.add(a.group(1)));
            }
        }
        componentCounts.forEach((name, count) -> md.append("| `").append(name).append("` | ").append(count).append(" | ")
                .append(String.join(", ", componentAttributes.get(name))).append(" |\n"));
        md.append("\n");

        List<HandlerCall> calls = new ArrayList<>();
        for (String url : files) {
            String text = index.page(url).text();
            for (MatchResult call : matches(handlerCall, text)) {
                calls.add(new HandlerCall(OperationsExtractor.event(text, call.start()), call.group(1), url));
            }
        }
        md.append("## Events and handler calls\n\n");
        Map<String, List<HandlerCall>> byEvent = new TreeMap<>();
        calls.forEach(call -> byEvent.computeIfAbsent(call.event(), k -> new ArrayList<>()).add(call));
        byEvent.forEach((event, eventCalls) -> {
            md.append("### ").append(event).append("\n\n");
            eventCalls.forEach(call -> md.append("- `").append(call.handler()).append("` (").append(call.file()).append(")\n"));
            md.append("\n");
        });
        md.append("Page-defined handlers: ").append(pageHandlers.isEmpty() ? "none" : "`" + String.join("`, `", pageHandlers) + "`").append("\n\n");

        Set<String> read = new TreeSet<>();
        Set<String> written = new TreeSet<>();
        Map<String, String> bundles = new TreeMap<>();
        Map<String, Set<String>> keys = new TreeMap<>();
        for (String url : files) {
            String text = index.page(url).text();
            matches(PAGE_SESSION_READ, text).forEach(m -> read.add(m.group(1) != null ? m.group(1) : m.group(2)));
            matches(PAGE_SESSION_WRITE, text).forEach(m -> written.add(m.group(1)));
            matches(BUNDLE, text).forEach(m -> bundles.putIfAbsent(m.group(1), m.group(2)));
            matches(RESOURCE_KEY, text).forEach(m -> keys.computeIfAbsent(m.group(1), k -> new TreeSet<>()).add(m.group(2)));
        }
        md.append("## Page session\n\n");
        md.append("- Written: ").append(codeList(written)).append("\n");
        md.append("- Read: ").append(codeList(read)).append("\n\n");

        md.append("## Resource bundle keys\n\n");
        keys.forEach((variable, variableKeys) -> md.append("- `").append(variable).append("` (")
                .append(bundles.getOrDefault(variable, "bundle not set in these files")).append("): ")
                .append(codeList(variableKeys)).append("\n"));
        md.append("\n");

        List<Map<String, Object>> pageOperations = operations.stream()
                .filter(operation -> ((List<?>) operation.get("screens")).contains(page.url()))
                .toList();
        md.append("## Admin REST endpoints\n\n| Methods | Endpoint | Sources |\n| --- | --- | --- |\n");
        pageOperations.forEach(operation -> md.append("| ").append(operation.get("httpMethods")).append(" | `")
                .append(operation.get("endpoint")).append("` | ").append(operation.get("sources")).append(" |\n"));
        md.append("\n");

        md.append("## Checklist\n\nJSFTemplating built-in handlers (page state and control flow, such as `setPageSessionAttribute` and `if`) "
                + "are listed under Events and handler calls but not here.\n\n");
        calls.stream().filter(call -> !builtinHandlers.contains(call.handler()))
                .forEach(call -> md.append("- [ ] ").append(call.event()).append(": `").append(call.handler()).append("` (")
                        .append(call.file()).append(")\n"));
        pageOperations.forEach(operation -> md.append("- [ ] REST ").append(operation.get("httpMethods")).append(" `")
                .append(operation.get("endpoint")).append("`\n"));
        return md.toString();
    }

    private static void includeTree(PageIndex index, String url, int depth, Set<String> path, StringBuilder out) {
        PageIndex.Page page = index.page(url);
        if (page == null) {
            return;
        }
        for (String include : page.includes()) {
            Set<String> targets = index.resolveAlias(include);
            String shown = targets.isEmpty() ? include + " (not found)" : String.join(", ", targets);
            out.append("  ".repeat(depth)).append("- `").append(shown).append("`");
            if (targets.stream().anyMatch(path::contains) || targets.contains(url)) {
                out.append(" (cycle)\n");
                continue;
            }
            out.append("\n");
            for (String target : targets) {
                Set<String> nextPath = new LinkedHashSet<>(path);
                nextPath.add(url);
                includeTree(index, target, depth + 1, nextPath, out);
            }
        }
    }

    private static List<MatchResult> matches(Pattern pattern, String text) {
        return pattern.matcher(text).results().toList();
    }

    private static String codeList(Set<String> values) {
        return values.isEmpty() ? "none" : "`" + String.join("`, `", values) + "`";
    }
}
