package runtime;

import com.microsoft.playwright.APIResponse;
import com.microsoft.playwright.Browser;
import com.microsoft.playwright.BrowserContext;
import com.microsoft.playwright.BrowserType;
import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;
import com.microsoft.playwright.PlaywrightException;
import com.microsoft.playwright.options.AriaRole;
import com.microsoft.playwright.options.FormData;
import com.microsoft.playwright.options.RequestOptions;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Supplier;

/**
 * Operation scenarios on the admin console (docs/試作計画.md P-8). The scenarios find elements by role, accessible
 * name and text only, so that the same scenario runs against a JSFTemplating page and its Facelets replacement. The
 * result of each step is written as scenario-&lt;name&gt;.yaml.
 */
final class Scenario {

    private static final double STEP_TIMEOUT = 30_000;
    private static final String POOL = "baselinePool";
    private static final String KEPT_RESOURCE = "jdbc/baseline";
    private static final String DELETED_RESOURCE = "jdbc/scenarioDelete";

    private final String baseUrl;
    private final List<Map<String, Object>> steps = new ArrayList<>();
    private final List<String> pageErrors = new ArrayList<>();
    private final List<String> consoleErrors = new ArrayList<>();
    /** Values recorded by a scenario for comparison, such as response headers. */
    private final Map<String, Object> recorded = new LinkedHashMap<>();

    Scenario(String baseUrl) {
        this.baseUrl = baseUrl.endsWith("/") ? baseUrl.substring(0, baseUrl.length() - 1) : baseUrl;
    }

    void run(String name, Path outputDirectory) throws IOException {
        if (!List.of("jdbc-resources", "jdbc-resource-new", "jdbc-resource-edit", "jdbc-security").contains(name)) {
            throw new IllegalArgumentException("Unknown scenario: " + name);
        }
        Map<String, Object> document = new LinkedHashMap<>();
        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(true));
            BrowserContext context = browser.newContext(new Browser.NewContextOptions()
                    .setViewportSize(1280, 1024).setLocale("en-US").setTimezoneId("UTC"));
            Page page = context.newPage();
            page.onPageError(error -> pageErrors.add(error.lines().findFirst().orElse(error)));
            page.onConsoleMessage(message -> {
                if ("error".equals(message.type())) {
                    consoleErrors.add(message.text());
                }
            });
            // The delete button asks for confirmation
            page.onDialog(dialog -> dialog.accept());
            try {
                new Crawler(baseUrl, false).login(page);
                if ("jdbc-resources".equals(name)) {
                    runJdbcResources(page);
                } else if ("jdbc-resource-new".equals(name)) {
                    runJdbcResourceNew(page);
                } else if ("jdbc-resource-edit".equals(name)) {
                    runJdbcResourceEdit(page);
                } else {
                    runJdbcSecurity(page);
                }
                // Only the Woodstock table renders this id; the Facelets page uses the plain table id
                openList(page);
                document.put("page", page.locator("[id='propertyForm:resourcesTable:_table']").count() > 0 ? "jsftemplating" : "facelets");
            } catch (RuntimeException e) {
                // Keep the steps recorded so far; the scenario is reported as failed
                String message = String.valueOf(e.getMessage()).replaceAll("\\s+", " ").strip();
                document.put("aborted", message.length() > 300 ? message.substring(0, 300) : message);
                steps.add(Map.of("name", "scenario aborted", "ok", false));
            }
            browser.close();
        }
        document.put("scenario", name);
        document.put("passed", steps.stream().allMatch(step -> Boolean.TRUE.equals(step.get("ok"))));
        document.put("steps", steps);
        document.put("pageErrors", pageErrors);
        document.put("consoleErrors", consoleErrors.size());
        document.put("consoleErrorSamples", consoleErrors.stream().distinct().limit(5).toList());
        document.put("recorded", recorded);
        Files.createDirectories(outputDirectory);
        Files.writeString(outputDirectory.resolve("scenario-" + name + ".yaml"),
                Yaml.write(document, "Generated by tools/runtime (scenario). Do not edit by hand."), StandardCharsets.UTF_8);
        System.out.println(name + ": " + (Boolean.TRUE.equals(document.get("passed")) ? "passed" : "failed"));
    }

    private void runJdbcResources(Page page) {
        step("open the list", () -> openList(page));
        step("the kept resource is enabled on its target", () -> waitForRowText(page, KEPT_RESOURCE, "Enabled on 1 of 1 Target(s)"));
        step("disable the kept resource", () -> {
            row(page, KEPT_RESOURCE).getByRole(AriaRole.CHECKBOX).check();
            button(page, "Disable").click();
            waitForRowText(page, KEPT_RESOURCE, "Enabled on 0 of 1 Target(s)");
        });
        step("enable the kept resource", () -> {
            row(page, KEPT_RESOURCE).getByRole(AriaRole.CHECKBOX).check();
            button(page, "Enable").click();
            waitForRowText(page, KEPT_RESOURCE, "Enabled on 1 of 1 Target(s)");
        });
        step("create a resource to delete (admin REST)", () -> {
            APIResponse response = page.request().post(baseUrl + "/management/domain/resources/jdbc-resource",
                    RequestOptions.create()
                            .setHeader("X-Requested-By", "GlassFish REST HTML interface")
                            .setHeader("Accept", "application/json")
                            .setHeader("Authorization", "Basic " + Base64.getEncoder().encodeToString("admin:".getBytes(StandardCharsets.UTF_8)))
                            .setForm(FormData.create().set("id", DELETED_RESOURCE).set("poolName", POOL)));
            if (!response.ok()) {
                throw new IllegalStateException("HTTP " + response.status() + " " + response.text());
            }
            openList(page);
            row(page, DELETED_RESOURCE).waitFor(new Locator.WaitForOptions().setTimeout(STEP_TIMEOUT));
        });
        step("delete the created resource", () -> {
            row(page, DELETED_RESOURCE).getByRole(AriaRole.CHECKBOX).check();
            button(page, "Delete").click();
            page.waitForCondition(() -> safeCount(rows(page, DELETED_RESOURCE)) == 0,
                    new Page.WaitForConditionOptions().setTimeout(STEP_TIMEOUT));
        });
    }

    private void runJdbcResourceNew(Page page) {
        String created = "jdbc/scenarioNew";
        step("open the new page", () -> {
            page.navigate(baseUrl + "/jdbc/jdbcResourceNew.jsf");
            page.getByRole(AriaRole.HEADING, new Page.GetByRoleOptions().setName("New JDBC Resource").setExact(true))
                    .waitFor(new Locator.WaitForOptions().setTimeout(STEP_TIMEOUT));
            page.getByLabel("JNDI Name:").waitFor(new Locator.WaitForOptions().setTimeout(STEP_TIMEOUT));
        });
        step("fill in the resource", () -> {
            page.getByLabel("JNDI Name:").fill(created);
            page.getByLabel("Pool Name:").selectOption(POOL);
            page.getByLabel("Description:").fill("created by the scenario");
        });
        step("choose the server as target", () -> {
            page.getByLabel("Available Targets:").selectOption("server");
            button(page, "Add >").click();
            page.waitForCondition(() -> {
                try {
                    return page.getByLabel("Available Targets:").textContent().indexOf("server") < 0;
                } catch (PlaywrightException e) {
                    return false;
                }
            }, new Page.WaitForConditionOptions().setTimeout(STEP_TIMEOUT));
        });
        step("create", () -> {
            button(page, "OK").click();
            page.getByRole(AriaRole.HEADING, new Page.GetByRoleOptions().setName("JDBC Resources").setExact(true))
                    .waitFor(new Locator.WaitForOptions().setTimeout(STEP_TIMEOUT));
            waitForRowText(page, created, "Enabled on 1 of 1 Target(s)");
        });
        step("the list shows the pool and the description", () -> {
            String text = row(page, created).textContent();
            if (!text.contains(POOL) || !text.contains("created by the scenario")) {
                throw new IllegalStateException("row text: " + text.strip());
            }
        });
        step("delete the created resource", () -> {
            row(page, created).getByRole(AriaRole.CHECKBOX).check();
            button(page, "Delete").click();
            page.waitForCondition(() -> safeCount(rows(page, created)) == 0,
                    new Page.WaitForConditionOptions().setTimeout(STEP_TIMEOUT));
        });
    }

    private void runJdbcResourceEdit(Page page) {
        String edited = "edited by the scenario";
        step("open the edit page", () -> openEdit(page));
        step("the page shows the resource", () -> {
            String order = page.getByLabel("Deployment Order:").inputValue();
            if (order.isEmpty()) {
                throw new IllegalStateException("deployment order: '" + order + "'");
            }
        });
        step("change the description and save", () -> {
            page.getByLabel("Description:").fill(edited);
            button(page, "Save").click();
            page.getByText("New values successfully saved.").waitFor(new Locator.WaitForOptions().setTimeout(STEP_TIMEOUT));
        });
        step("the saved description is shown again", () -> {
            openEdit(page);
            String description = page.getByLabel("Description:").inputValue();
            if (!edited.equals(description)) {
                throw new IllegalStateException("description: '" + description + "'");
            }
        });
        step("the list shows the description", () -> {
            openList(page);
            waitForRowText(page, KEPT_RESOURCE, edited);
        });
        step("restore the description", () -> {
            openEdit(page);
            page.getByLabel("Description:").fill("");
            button(page, "Save").click();
            page.getByText("New values successfully saved.").waitFor(new Locator.WaitForOptions().setTimeout(STEP_TIMEOUT));
            openEdit(page);
            String description = page.getByLabel("Description:").inputValue();
            if (!description.isEmpty()) {
                throw new IllegalStateException("description: '" + description + "'");
            }
        });
        step("open the Target tab", () -> {
            page.getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("Target").setExact(true)).click();
            page.getByRole(AriaRole.HEADING, new Page.GetByRoleOptions().setName("Resource Targets").setExact(true))
                    .waitFor(new Locator.WaitForOptions().setTimeout(STEP_TIMEOUT));
        });
    }

    /**
     * Security category A checks (docs/as-is/security-as-is.md chapter 9) on the JDBC resource pages: output is escaped,
     * a post without the view state changes nothing, and the response headers are recorded for comparison.
     */
    private void runJdbcSecurity(Page page) {
        String resource = "jdbc/scenarioEscape";
        String markup = "<img src=x onerror=\"window.__scenarioInjected=1\">";
        String restUrl = baseUrl + "/management/domain/resources/jdbc-resource";
        // Options carry the form of a request, so each request gets its own
        Supplier<RequestOptions> restOptions = () -> RequestOptions.create()
                .setHeader("X-Requested-By", "GlassFish REST HTML interface")
                .setHeader("Accept", "application/json")
                .setHeader("Authorization", "Basic " + Base64.getEncoder().encodeToString("admin:".getBytes(StandardCharsets.UTF_8)));
        step("create a resource whose description is markup (admin REST)", () -> {
            // A previous run may have stopped before deleting it
            page.request().delete(restUrl + "/" + resource.replace("/", "%2F"), restOptions.get());
            APIResponse response = page.request().post(restUrl, restOptions.get()
                    .setForm(FormData.create().set("id", resource).set("poolName", POOL).set("description", markup)));
            if (!response.ok()) {
                throw new IllegalStateException("HTTP " + response.status() + " " + response.text());
            }
        });
        step("the list shows the markup as text", () -> {
            openList(page);
            waitForRowText(page, resource, markup);
            if (Boolean.TRUE.equals(page.evaluate("() => window.__scenarioInjected === 1"))) {
                throw new IllegalStateException("the description was rendered as markup");
            }
        });
        step("the edit page shows the markup as the field value", () -> {
            page.navigate(baseUrl + "/jdbc/jdbcResourceEdit.jsf?name=" + resource);
            page.getByLabel("Description:").waitFor(new Locator.WaitForOptions().setTimeout(STEP_TIMEOUT));
            String value = page.getByLabel("Description:").inputValue();
            if (!markup.equals(value) || Boolean.TRUE.equals(page.evaluate("() => window.__scenarioInjected === 1"))) {
                throw new IllegalStateException("description field: '" + value + "'");
            }
        });
        step("a post without the view state deletes nothing", () -> {
            openList(page);
            // Field names of both the JSFTemplating table and the Facelets table for the first rows and the delete button
            FormData form = FormData.create()
                    .set("propertyForm", "propertyForm")
                    .set("propertyForm:deleteButton", "Delete")
                    .set("propertyForm:resourcesTable:topActionsGroup1:button1", "Delete");
            for (int i = 0; i < 5; i++) {
                form.set("propertyForm:rows:" + i + ":select", "on");
                form.set("propertyForm:resourcesTable:rowGroup1:" + i + ":col0:select", "true");
            }
            APIResponse post = page.request().post(baseUrl + "/jdbc/jdbcResources.jsf", RequestOptions.create().setForm(form));
            recorded.put("postWithoutViewStateStatus", post.status());
            APIResponse check = page.request().get(restUrl + "/" + resource.replace("/", "%2F"), restOptions.get());
            if (!check.ok()) {
                throw new IllegalStateException("the resource is gone: HTTP " + check.status());
            }
        });
        step("record the response headers of the list page", () -> {
            APIResponse response = page.request().get(baseUrl + "/jdbc/jdbcResources.jsf");
            Map<String, Object> headers = new LinkedHashMap<>();
            for (String name : List.of("x-frame-options", "content-security-policy", "x-content-type-options", "cache-control",
                    "referrer-policy", "strict-transport-security", "content-type")) {
                headers.put(name, response.headers().get(name));
            }
            recorded.put("listPageHeaders", headers);
        });
        step("delete the resource (admin REST)", () -> {
            APIResponse response = page.request().delete(restUrl + "/" + resource.replace("/", "%2F"), restOptions.get());
            if (!response.ok()) {
                throw new IllegalStateException("HTTP " + response.status() + " " + response.text());
            }
        });
    }

    private void openEdit(Page page) {
        page.navigate(baseUrl + "/jdbc/jdbcResourceEdit.jsf?name=" + KEPT_RESOURCE);
        page.getByRole(AriaRole.HEADING, new Page.GetByRoleOptions().setName("Edit JDBC Resource").setExact(true))
                .waitFor(new Locator.WaitForOptions().setTimeout(STEP_TIMEOUT));
        page.getByLabel("Description:").waitFor(new Locator.WaitForOptions().setTimeout(STEP_TIMEOUT));
    }

    private void openList(Page page) {
        page.navigate(baseUrl + "/jdbc/jdbcResources.jsf");
        page.getByRole(AriaRole.HEADING, new Page.GetByRoleOptions().setName("JDBC Resources").setExact(true))
                .waitFor(new Locator.WaitForOptions().setTimeout(STEP_TIMEOUT));
        page.getByRole(AriaRole.CHECKBOX).first().waitFor(new Locator.WaitForOptions().setTimeout(STEP_TIMEOUT));
    }

    /** Table rows that show the resource name; layout tables around the list may match too, so the innermost is last. */
    private static Locator rows(Page page, String resourceName) {
        return page.getByRole(AriaRole.ROW)
                .filter(new Locator.FilterOptions().setHasText(resourceName))
                .filter(new Locator.FilterOptions().setHas(page.getByRole(AriaRole.CHECKBOX)));
    }

    private static Locator row(Page page, String resourceName) {
        return rows(page, resourceName).last();
    }

    private static Locator button(Page page, String name) {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName(name).setExact(true));
    }

    private static void waitForRowText(Page page, String resourceName, String text) {
        page.waitForCondition(() -> {
            try {
                return safeCount(rows(page, resourceName)) > 0 && row(page, resourceName).textContent().contains(text);
            } catch (PlaywrightException e) {
                // The page is being replaced (the JSFTemplating page redirects after an action)
                return false;
            }
        }, new Page.WaitForConditionOptions().setTimeout(STEP_TIMEOUT));
    }

    private static int safeCount(Locator locator) {
        try {
            return locator.count();
        } catch (PlaywrightException e) {
            return -1;
        }
    }

    private void step(String name, Runnable action) {
        Map<String, Object> step = new LinkedHashMap<>();
        step.put("name", name);
        long start = System.currentTimeMillis();
        boolean previousFailed = steps.stream().anyMatch(s -> !Boolean.TRUE.equals(s.get("ok")));
        if (previousFailed) {
            step.put("ok", null);
            step.put("error", "skipped after a failed step");
        } else {
            try {
                action.run();
                step.put("ok", true);
                step.put("error", null);
            } catch (RuntimeException | AssertionError e) {
                step.put("ok", false);
                String message = e.getMessage() == null ? e.getClass().getName() : e.getMessage();
                String flat = message.replaceAll("\\s+", " ").strip();
                step.put("error", flat.length() > 300 ? flat.substring(0, 300) : flat);
            }
        }
        step.put("millis", System.currentTimeMillis() - start);
        steps.add(step);
        System.out.println((Boolean.TRUE.equals(step.get("ok")) ? "ok " : "ng ") + name);
    }
}
