package runtime;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeSet;
import java.util.stream.Stream;

import javax.imageio.ImageIO;

/**
 * Compares the screenshots of two crawls of the same console, file by file, to see how much the pictures vary between
 * runs in the same environment. The result is the basis for the tolerance of the screenshot comparison (S11).
 */
final class ScreenshotDiff {

    /** Upper bounds of the share of differing pixels used for the distribution in the summary. */
    private static final double[] BUCKETS = {0.0, 0.0001, 0.001, 0.01, 0.05, 1.0};

    private ScreenshotDiff() {
    }

    static void write(Path first, Path second, Path output) throws IOException {
        TreeSet<String> names = new TreeSet<>(pngNames(first));
        TreeSet<String> secondNames = new TreeSet<>(pngNames(second));
        List<String> onlyFirst = names.stream().filter(n -> !secondNames.contains(n)).toList();
        List<String> onlySecond = secondNames.stream().filter(n -> !names.contains(n)).toList();
        names.retainAll(secondNames);

        List<Map<String, Object>> differing = new ArrayList<>();
        int[] distribution = new int[BUCKETS.length];
        int sizeMismatches = 0;
        for (String name : names) {
            BufferedImage a = ImageIO.read(first.resolve(name).toFile());
            BufferedImage b = ImageIO.read(second.resolve(name).toFile());
            Map<String, Object> entry = new LinkedHashMap<>();
            entry.put("file", name);
            if (a.getWidth() != b.getWidth() || a.getHeight() != b.getHeight()) {
                sizeMismatches++;
                entry.put("size", a.getWidth() + "x" + a.getHeight() + " / " + b.getWidth() + "x" + b.getHeight());
                differing.add(entry);
                continue;
            }
            long pixels = (long) a.getWidth() * a.getHeight();
            long changed = 0;
            int maxDelta = 0;
            for (int y = 0; y < a.getHeight(); y++) {
                for (int x = 0; x < a.getWidth(); x++) {
                    int pa = a.getRGB(x, y);
                    int pb = b.getRGB(x, y);
                    if (pa != pb) {
                        changed++;
                        for (int shift = 0; shift <= 16; shift += 8) {
                            maxDelta = Math.max(maxDelta, Math.abs(((pa >> shift) & 0xff) - ((pb >> shift) & 0xff)));
                        }
                    }
                }
            }
            double share = pixels == 0 ? 0 : (double) changed / pixels;
            for (int i = 0; i < BUCKETS.length; i++) {
                if (share <= BUCKETS[i]) {
                    distribution[i]++;
                    break;
                }
            }
            if (changed > 0) {
                entry.put("size", a.getWidth() + "x" + a.getHeight());
                entry.put("changedPixels", changed);
                entry.put("changedShare", String.format("%.6f", share));
                entry.put("maxChannelDelta", maxDelta);
                differing.add(entry);
            }
        }

        Map<String, Object> buckets = new LinkedHashMap<>();
        buckets.put("identical", distribution[0]);
        for (int i = 1; i < BUCKETS.length; i++) {
            buckets.put("changedShareUpTo" + BUCKETS[i], distribution[i]);
        }
        Map<String, Object> summary = new LinkedHashMap<>();
        summary.put("compared", names.size());
        summary.put("sizeMismatches", sizeMismatches);
        summary.put("distribution", buckets);
        summary.put("onlyInFirst", onlyFirst);
        summary.put("onlyInSecond", onlySecond);
        Map<String, Object> document = new LinkedHashMap<>();
        document.put("source", Map.of("first", first.toString().replace('\\', '/'), "second", second.toString().replace('\\', '/')));
        document.put("summary", summary);
        document.put("differing", differing);
        Files.writeString(output, Yaml.write(document,
                "Generated by tools/runtime (compare-screenshots). Do not edit by hand.\n"
                        + "Pixel differences between the screenshots of two crawls; interpretation belongs in docs/as-is/runtime-observations.md."),
                StandardCharsets.UTF_8);
    }

    private static List<String> pngNames(Path directory) throws IOException {
        try (Stream<Path> files = Files.list(directory)) {
            return files.map(p -> p.getFileName().toString()).filter(n -> n.endsWith(".png")).sorted().toList();
        }
    }
}
